import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PropertyCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  address: string;
  @ApiProperty()
  rent_amount: string;
  @ApiProperty()
  status: string;
}

export class Property {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  address: string;
  @ApiProperty()
  rent_amount: string;
  @ApiProperty()
  status: string;
}
